// Package db provides database access layer for the file-vault service.
//
// This package is auto-generated by sqlc from SQL queries in migrations/queries/.
// It provides type-safe database operations for all entities.
//
// Generated Files
//
//   - db.go: Database connection and Queries struct
//   - models.go: Go struct definitions for database tables
//   - *.sql.go: Generated SQL query functions
//
// Tables
//
//   - users: User accounts (id, name, email, password_hash, created_at)
//   - refresh_tokens: JWT refresh tokens (token, user_id, expires_at)
//   - files: Uploaded file metadata (id, user_id, file_name, file_url, created_at)
//
// Main Operations
//
//   - CreateUser: Insert new user
//   - GetUserByEmail: Find user by email
//   - CreateFile: Insert file metadata after S3 upload
//   - GetFilesByUser: List all files for a user
//   - GetFileByID: Get single file by ID (with user ownership check)
//   - DeleteFileByID: Delete file (with user ownership check)
//   - CreateRefreshToken: Store refresh token
//   - GetRefreshToken: Retrieve refresh token
//   - DeleteRefreshToken: Remove refresh token (logout)
//
// Usage
//
// The package is used by handlers and CLI to interact with PostgreSQL.
// Connection is managed via pgx/v5 and wrapped in a Queries struct
// for convenient type-safe operations.
package db