// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: logs.sql

package db

import (
	"context"
)

const createRequestLog = `-- name: CreateRequestLog :exec
INSERT INTO
    request_logs (
        method,
        path,
        status,
        latency_ms,
        request_id,
        user_id
    )
VALUES
    ($1, $2, $3, $4, $5, $6)
`

type CreateRequestLogParams struct {
	Method    string
	Path      string
	Status    int32
	LatencyMs int64
	RequestID string
	UserID    string
}

func (q *Queries) CreateRequestLog(ctx context.Context, arg CreateRequestLogParams) error {
	_, err := q.db.Exec(ctx, createRequestLog,
		arg.Method,
		arg.Path,
		arg.Status,
		arg.LatencyMs,
		arg.RequestID,
		arg.UserID,
	)
	return err
}

const getRequestLogs = `-- name: GetRequestLogs :many
SELECT
    id, method, path, status, latency_ms, request_id, user_id, created_at
FROM
    request_logs
ORDER BY
    created_at DESC
LIMIT
    100
`

func (q *Queries) GetRequestLogs(ctx context.Context) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getRequestLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.RequestID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestLogsByStatus = `-- name: GetRequestLogsByStatus :many
SELECT
    id, method, path, status, latency_ms, request_id, user_id, created_at
FROM
    request_logs
WHERE
    status = $1
ORDER BY
    created_at DESC
LIMIT
    100
`

func (q *Queries) GetRequestLogsByStatus(ctx context.Context, status int32) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getRequestLogsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.RequestID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestLogsByUser = `-- name: GetRequestLogsByUser :many
SELECT
    id, method, path, status, latency_ms, request_id, user_id, created_at
FROM
    request_logs
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT
    100
`

func (q *Queries) GetRequestLogsByUser(ctx context.Context, userID string) ([]RequestLog, error) {
	rows, err := q.db.Query(ctx, getRequestLogsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestLog
	for rows.Next() {
		var i RequestLog
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.LatencyMs,
			&i.RequestID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
