// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FileName  string
	FileUrl   string
	CreatedAt pgtype.Timestamptz
	FileSize  int64
}

type RefreshToken struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type RequestLog struct {
	ID        pgtype.UUID
	Method    string
	Path      string
	Status    int32
	LatencyMs int64
	RequestID string
	UserID    string
	CreatedAt pgtype.Timestamp
}

type ShareLink struct {
	ID            pgtype.UUID
	FileID        pgtype.UUID
	Token         string
	CreatedBy     pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	PasswordHash  pgtype.Text
	MaxDownloads  pgtype.Int4
	DownloadCount pgtype.Int4
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Provider       string
	ProviderID     string
	Otp            pgtype.Text
	OtpExpiresAt   pgtype.Timestamp
	VerifiedAt     pgtype.Timestamp
}
