// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FileName  string
	FileUrl   string
	CreatedAt pgtype.Timestamptz
}

type RefreshToken struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID             pgtype.UUID
	Email          string
	Name           string
	HashedPassword string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	Provider       string
	ProviderID     string
}
