// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const markUserVerified = `-- name: MarkUserVerified :exec
UPDATE users
SET
    verified_at = NOW(),
    otp = NULL,
    otp_expires_at = NULL
WHERE
    id = $1
`

func (q *Queries) MarkUserVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markUserVerified, id)
	return err
}

const saveOTP = `-- name: SaveOTP :exec
UPDATE users
SET
    otp = $1,
    otp_expires_at = $2
WHERE
    id = $3
`

type SaveOTPParams struct {
	Otp          pgtype.Text
	OtpExpiresAt pgtype.Timestamp
	ID           pgtype.UUID
}

func (q *Queries) SaveOTP(ctx context.Context, arg SaveOTPParams) error {
	_, err := q.db.Exec(ctx, saveOTP, arg.Otp, arg.OtpExpiresAt, arg.ID)
	return err
}
