// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO share_links (file_id, token, created_by, expires_at, password_hash, max_downloads)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, file_id, token, created_by, expires_at, password_hash, max_downloads, download_count, created_at
`

type CreateShareLinkParams struct {
	FileID       pgtype.UUID
	Token        string
	CreatedBy    pgtype.UUID
	ExpiresAt    pgtype.Timestamptz
	PasswordHash pgtype.Text
	MaxDownloads pgtype.Int4
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.FileID,
		arg.Token,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.PasswordHash,
		arg.MaxDownloads,
	)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteShareLink = `-- name: DeleteShareLink :exec
DELETE FROM share_links
WHERE id = $1 AND created_by = $2
`

type DeleteShareLinkParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) DeleteShareLink(ctx context.Context, arg DeleteShareLinkParams) error {
	_, err := q.db.Exec(ctx, deleteShareLink, arg.ID, arg.CreatedBy)
	return err
}

const getShareLinkByID = `-- name: GetShareLinkByID :one
SELECT id, file_id, token, created_by, expires_at, password_hash, max_downloads, download_count, created_at
FROM share_links
WHERE id = $1 AND created_by = $2
`

type GetShareLinkByIDParams struct {
	ID        pgtype.UUID
	CreatedBy pgtype.UUID
}

func (q *Queries) GetShareLinkByID(ctx context.Context, arg GetShareLinkByIDParams) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByID, arg.ID, arg.CreatedBy)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, file_id, token, created_by, expires_at, password_hash, max_downloads, download_count, created_at
FROM share_links
WHERE token = $1
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (ShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByToken, token)
	var i ShareLink
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.Token,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.PasswordHash,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
	)
	return i, err
}

const getShareLinksByFileID = `-- name: GetShareLinksByFileID :many
SELECT id, file_id, token, created_by, expires_at, password_hash, max_downloads, download_count, created_at
FROM share_links
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetShareLinksByFileID(ctx context.Context, fileID pgtype.UUID) ([]ShareLink, error) {
	rows, err := q.db.Query(ctx, getShareLinksByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareLink
	for rows.Next() {
		var i ShareLink
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.MaxDownloads,
			&i.DownloadCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShareLinksByUser = `-- name: GetShareLinksByUser :many
SELECT sl.id, sl.file_id, sl.token, sl.created_by, sl.expires_at, sl.password_hash, sl.max_downloads, sl.download_count, sl.created_at, f.file_name
FROM share_links sl
JOIN files f ON sl.file_id = f.id
WHERE sl.created_by = $1
ORDER BY sl.created_at DESC
LIMIT $2 OFFSET $3
`

type GetShareLinksByUserParams struct {
	CreatedBy pgtype.UUID
	Limit     int32
	Offset    int32
}

type GetShareLinksByUserRow struct {
	ID            pgtype.UUID
	FileID        pgtype.UUID
	Token         string
	CreatedBy     pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	PasswordHash  pgtype.Text
	MaxDownloads  pgtype.Int4
	DownloadCount pgtype.Int4
	CreatedAt     pgtype.Timestamptz
	FileName      string
}

func (q *Queries) GetShareLinksByUser(ctx context.Context, arg GetShareLinksByUserParams) ([]GetShareLinksByUserRow, error) {
	rows, err := q.db.Query(ctx, getShareLinksByUser, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShareLinksByUserRow
	for rows.Next() {
		var i GetShareLinksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.Token,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.PasswordHash,
			&i.MaxDownloads,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.FileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementDownloadCount = `-- name: IncrementDownloadCount :exec
UPDATE share_links
SET download_count = download_count + 1
WHERE id = $1
`

func (q *Queries) IncrementDownloadCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementDownloadCount, id)
	return err
}
