// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO
    files (user_id, file_name, file_url, file_size)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, user_id, file_name, file_url, created_at, file_size
`

type CreateFileParams struct {
	UserID   pgtype.UUID
	FileName string
	FileUrl  string
	FileSize int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.FileName,
		arg.FileUrl,
		arg.FileSize,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files
WHERE
    id = $1
    AND user_id = $2
`

type DeleteFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteFileByID(ctx context.Context, arg DeleteFileByIDParams) error {
	_, err := q.db.Exec(ctx, deleteFileByID, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT
    id, user_id, file_name, file_url, created_at, file_size
FROM
    files
WHERE
    id = $1
    AND user_id = $2
`

type GetFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const getFilesByUser = `-- name: GetFilesByUser :many
SELECT
    id, user_id, file_name, file_url, file_size, created_at
FROM
    files
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT
    $2
OFFSET
    $3
`

type GetFilesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type GetFilesByUserRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FileName  string
	FileUrl   string
	FileSize  int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFilesByUser(ctx context.Context, arg GetFilesByUserParams) ([]GetFilesByUserRow, error) {
	rows, err := q.db.Query(ctx, getFilesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesByUserRow
	for rows.Next() {
		var i GetFilesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilesFiltered = `-- name: GetFilesFiltered :many
SELECT id, user_id, file_name, file_url, file_size, created_at
FROM files
WHERE user_id = $1
AND (COALESCE($4, '') = '' OR file_name ILIKE '%' || $4 || '%')
AND (
    COALESCE($5, '') = '' OR
    ($5 = 'image' AND (file_url ILIKE '%.jpg' OR file_url ILIKE '%.jpeg' OR file_url ILIKE '%.png' OR file_url ILIKE '%.gif' OR file_url ILIKE '%.webp' OR file_url ILIKE '%.svg' OR file_url ILIKE '%.JPG' OR file_url ILIKE '%.PNG')) OR
    ($5 = 'video' AND (file_url ILIKE '%.mp4' OR file_url ILIKE '%.webm' OR file_url ILIKE '%.mov' OR file_url ILIKE '%.avi' OR file_url ILIKE '%.mkv' OR file_url ILIKE '%.MP4')) OR
    ($5 = 'document' AND (file_url ILIKE '%.pdf' OR file_url ILIKE '%.doc' OR file_url ILIKE '%.txt' OR file_url ILIKE '%.PDF'))
)
ORDER BY
    CASE WHEN $2 = 'name' THEN file_name END ASC,
    CASE WHEN $2 = 'size' THEN file_size END DESC,
    CASE WHEN $2 = '' OR $2 = 'date' THEN created_at END DESC
LIMIT $3 OFFSET $6
`

type GetFilesFilteredParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Limit   int32
	Column4 interface{}
	Column5 interface{}
	Offset  int32
}

type GetFilesFilteredRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	FileName  string
	FileUrl   string
	FileSize  int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetFilesFiltered(ctx context.Context, arg GetFilesFilteredParams) ([]GetFilesFilteredRow, error) {
	rows, err := q.db.Query(ctx, getFilesFiltered,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Column4,
		arg.Column5,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesFilteredRow
	for rows.Next() {
		var i GetFilesFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.FileSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFiles = `-- name: SearchFiles :many
SELECT
    id, user_id, file_name, file_url, created_at, file_size
FROM
    files
WHERE
    user_id = $1
    AND file_name ILIKE '%' || $2 || '%'
ORDER BY
    created_at DESC
LIMIT
    $3
`

type SearchFilesParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Text
	Limit   int32
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.CreatedAt,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
