// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO
    files (user_id, file_name, file_url)
VALUES
    ($1, $2, $3)
RETURNING
    id, user_id, file_name, file_url, created_at
`

type CreateFileParams struct {
	UserID   pgtype.UUID
	FileName string
	FileUrl  string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile, arg.UserID, arg.FileName, arg.FileUrl)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files
WHERE
    id = $1
    AND user_id = $2
`

type DeleteFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteFileByID(ctx context.Context, arg DeleteFileByIDParams) error {
	_, err := q.db.Exec(ctx, deleteFileByID, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT
    id, user_id, file_name, file_url, created_at
FROM
    files
WHERE
    id = $1
    AND user_id = $2
`

type GetFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getFilesByUser = `-- name: GetFilesByUser :many
SELECT
    id, user_id, file_name, file_url, created_at
FROM
    files
WHERE
    user_id = $1
ORDER BY
    created_at DESC
`

func (q *Queries) GetFilesByUser(ctx context.Context, userID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
