// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO
    files (user_id, file_name, file_url, file_size)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, user_id, file_name, file_url, created_at, file_size
`

type CreateFileParams struct {
	UserID   pgtype.UUID
	FileName string
	FileUrl  string
	FileSize int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.UserID,
		arg.FileName,
		arg.FileUrl,
		arg.FileSize,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const deleteFileByID = `-- name: DeleteFileByID :exec
DELETE FROM files
WHERE
    id = $1
    AND user_id = $2
`

type DeleteFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteFileByID(ctx context.Context, arg DeleteFileByIDParams) error {
	_, err := q.db.Exec(ctx, deleteFileByID, arg.ID, arg.UserID)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT
    id, user_id, file_name, file_url, created_at, file_size
FROM
    files
WHERE
    id = $1
    AND user_id = $2
`

type GetFileByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, arg.ID, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileName,
		&i.FileUrl,
		&i.CreatedAt,
		&i.FileSize,
	)
	return i, err
}

const getFilesByUser = `-- name: GetFilesByUser :many
SELECT
    id, user_id, file_name, file_url, created_at, file_size
FROM
    files
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT
    $2
OFFSET
    $3
`

type GetFilesByUserParams struct {
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetFilesByUser(ctx context.Context, arg GetFilesByUserParams) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.CreatedAt,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFiles = `-- name: SearchFiles :many
SELECT
    id, user_id, file_name, file_url, created_at, file_size
FROM
    files
WHERE
    user_id = $1
    AND file_name ILIKE '%' || $2 || '%'
ORDER BY
    created_at DESC
LIMIT
    $3
`

type SearchFilesParams struct {
	UserID  pgtype.UUID
	Column2 pgtype.Text
	Limit   int32
}

func (q *Queries) SearchFiles(ctx context.Context, arg SearchFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, searchFiles, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileName,
			&i.FileUrl,
			&i.CreatedAt,
			&i.FileSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
