// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, name, hashed_password, provider, provider_id)
VALUES
    ($1, $2, $3, $4, $5)
RETURNING
    id, email, name, hashed_password, created_at, updated_at, provider, provider_id, otp, otp_expires_at, verified_at
`

type CreateUserParams struct {
	Email          string
	Name           string
	HashedPassword string
	Provider       string
	ProviderID     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.HashedPassword,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.Otp,
		&i.OtpExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, email, name, hashed_password, created_at, updated_at, provider, provider_id, otp, otp_expires_at, verified_at
FROM
    users
WHERE
    email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.Otp,
		&i.OtpExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, email, name, hashed_password, created_at, updated_at, provider, provider_id, otp, otp_expires_at, verified_at
FROM
    users
WHERE
    id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Provider,
		&i.ProviderID,
		&i.Otp,
		&i.OtpExpiresAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT
    id, email, name, hashed_password, created_at, updated_at, provider, provider_id, otp, otp_expires_at, verified_at
FROM
    users
LIMIT
    30
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.HashedPassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Provider,
			&i.ProviderID,
			&i.Otp,
			&i.OtpExpiresAt,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
